[character]
success_symbol = "ğŸ§ [â¯](bold green)"
error_symbol = "ğŸ§ [â¯](bold red)"

[directory]
truncation_length = 10
truncate_to_repo = false

[git_metrics]
disabled = false

[git_status]
format = '([\[$staged\]]($style) )'
staged = '[++\($count\)](green)'

[username]
style_user = "white bold"
format = "[$user]($style): "
show_always = true

[time]
disabled = false
format = "[$time]($style) "
time_format = '%R'

[docker_context]
disabled = true

[package]
disabled = true
